### PR TITLE
Add instructions for working around docker-py bug.

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @andymckay

### CODE REVIEW

**Comment by muffinresearch** [comment]
What versions of boot2docker are you using? Do the CLI and the vm version match?

`mkt versions` should tell you this info.

**Comment by chuckharmston** [comment]
$ mkt versions
    usage: mkt [-h] [--version]
               {root,bash,update,check,up,chkgitconfig,revs,whoami,checkout,bind}
               ...
    mkt: error: invalid choice: 'versions' (choose from 'root', 'bash', 'update', 'check', 'up', 'chkgitconfig', 'revs', 'whoami', 'checkout', 'bind')

In the host:

    $ boot2docker version
    Boot2Docker-cli version: v1.4.1
    Git commit: 43241cb

In the guest:

    $ boot2docker --version
    -sh: boot2docker: not found

**Comment by muffinresearch** [comment]
Hmm, that should have been `mkt check --versions` but I don't see any output trying that myself. I'll file a bug for that.

For the guest bit - you could try `boot2docker ssh 'docker --version'`. boot2docker won't exist on the guest as that is the boot2docker vm.

**Comment by chuckharmston** [comment]
$ boot2docker ssh 'docker --version'
    Docker version 1.4.1, build 5bc2ff8

**Comment by muffinresearch** [comment]
I can't repro with pkg installed 1.4.1 but the workaround seems ok. r+

**Pull request merged**
