### PR TITLE
Correct documentation for restarting Docker on OS X.

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @robhudson

### CODE REVIEW

**Comment by robhudson** [comment]
I'd say `r+` b/c that's what I do but it was recently changed by @eviljeff [here].(https://github.com/mozilla/marketplace-docs/commit/9b9d5e931adadf8f1728fc2787cadb01cbb2489a)

**Comment by chuckharmston** [comment]
Uh...the existing command actually just doesn't work for me:

```shell
$ docker-compose start -d
Start existing containers.

Usage: start [SERVICE...]
```

**Comment by robhudson** [comment]
Me either. :shipit:

**Comment by chuckharmston** [comment]
Sorry @eviljeff, if there's something we're missing, let us know?

**Comment by eviljeff** [comment]
I can only comment on what works for me on Ubuntu.  If the opposite works on MacOS then :+1:

**Pull request merged**
